#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

new='\trewrite ^/redirect_me https://youtu.be/PF5GBT9oJDo permanent;'
lineNo=47
FILE='/etc/nginx/sites-available/default'
FILE2='/etc/nginx/sites-enabled/default'
sed -i "${lineNo}s~.*~${new}~" $FILE
sed -i "${lineNo}s~.*~${new}~" $FILE2
sudo service nginx restart
