#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.
# When a page/file not found in the document root is requested, the 404.html
# page is served to the client as stated with the error_page directive.

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new='\trewrite ^/redirect_me https://youtu.be/PF5GBT9oJDo permanent;'
new2='\terror_page 404 /404.html;\n'
lineNo=47
lineNo2=24
FILE='/etc/nginx/sites-available/default'
FILE2='/etc/nginx/sites-enabled/default'
sed -i "${lineNo}s~.*~${new}~" $FILE
sed -i "${lineNo}s~.*~${new}~" $FILE2
sed -i "${lineNo2}s~.*~${new2}~" $FILE
sed -i "${lineNo2}s~.*~${new2}~" $FILE2
sudo service nginx restart
