#!/usr/bin/env bash
#server config
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
lineNo3=24
replace='\tadd_header X-Served-By $hostname;\n'
FILE='/etc/nginx/sites-available/default'
FILE2='/etc/nginx/sites-enabled/default'
sed -i "${lineNo3}s~.*~${replace}~" $FILE
sed -i "${lineNo3}s~.*~${replace}~" $FILE2
service nginx start